server:
  port: 9100
  context-path: /api/baby

info:
  component: Service Registration and Discovery

spring:
  profiles:
    active: development
  devtools.livereload.enabled: false
  jmx.default-domain: ${spring.application.name}
  output.ansi.enabled: always
  jooq:
    sql-dialect: MYSQL
  datasource:
      platform: mysql
      url: jdbc:mysql://localhost:3306/baby?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
      username: root
      password: fengshuaiju
      initialization-mode: never
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
    deserialization:
      READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
    date-format: yyyy-MM-dd
  cloud:
    stream:
      bindings:
        output:
          destination: feng.baby.notifications
        from-self:
          group: feng.baby
          destination: feng.baby.notifications
        from-uaa:
          group: feng.baby
          destination: feng.uaa.notifications

  rabbitmq:
    host: broker
    port: 5672

eureka:
  instance:
    metadataMap:
      instanceId:
        ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetchRegistry: true
    healthcheck:
      enabled: true

security:
  oauth2:
    resource:
      jwt:
        key-value: staging

appId: 1252541513
secretId: AKIDNaYIn4btRmtlPoHuc5KK6dz6xYt2NYv2
secretKey: 2pNgngLn13rRoyud8QVM0RffT1IK5apo
tencent.file.path: https://fengshuaiju-1252541513.cos.ap-beijing.myqcloud.com


logging:
  file: ${user.home}/logs/baby.log

---
spring:
  profiles: staging

appId: 1252541513
secretId: AKIDNaYIn4btRmtlPoHuc5KK6dz6xYt2NYv2
secretKey: 2pNgngLn13rRoyud8QVM0RffT1IK5apo
tencent.file.path: https://fengshuaiju-1252541513.cos.ap-beijing.myqcloud.com