spring:
  application:
    name: baby
  profiles:
    active: development
server:
  context-path: "/api/baby"
  tomcat:
    protocol-header-https-value: "https"
    protocol-header: "X-Forwarded-Proto"
    remote-ip-header: "X-Forwarded-For"