server:
  port: 9000
  context-path: /api/baby

info:
  component: Service Registration and Discovery

spring:
  profiles:
    active: development
  devtools.livereload.enabled: false
  jmx.default-domain: ${spring.application.name}
  output.ansi.enabled: always

eureka:
  instance:
    metadataMap:
      instanceId:
        ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetchRegistry: true
    healthcheck:
      enabled: true

security:
  oauth2:
    resource:
      jwt:
        key-value: staging